on:
  push:
    branches: master

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.4

    - name: Caching dependencies to speed up workflows
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ matrix.os }}-${{ hashFiles('**/lockfiles','**/requirements*.txt') }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Test URL(s)
      run: |
        xargs -L1 -a test_data/urls.txt curl -so /dev/null -w '%{url} %{http_code} %{redirect_url}\n' | column -t -s' ' | sort
    
    - name: Test if the source will compile, a sanity check
      working-directory: src/
      run: |
        python -m compileall .
        
    - name: Pause to allow Bitly's API to update, and avoid a race condition
      run: |
        sleep 5
    
    - name: Test source code
      env:
        BITLY_API_TOKEN: ${{secrets.BITLY_API_TOKEN}}
      run: |
          python3 -m unittest
